AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Knowledge Hub API - FastAPI on Lambda with DynamoDB

Parameters:
  CORSOrigins:
    Type: String
    Default: "http://localhost:5173,http://localhost:4173"
    Description: Comma-separated list of allowed CORS origins
  JWTSecretKey:
    Type: String
    NoEcho: true
    Description: JWT secret key for token signing
    Default: "change-me-in-production"

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-tags"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tag_id
          AttributeType: S
      KeySchema:
        - AttributeName: tag_id
          KeyType: HASH

  ResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-resources"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: resource_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: resource_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
          TAGS_TABLE_NAME: !Ref TagsTable
          RESOURCES_TABLE_NAME: !Ref ResourcesTable
          CORS_ORIGINS: !Ref CORSOrigins
          JWT_SECRET_KEY: !Ref JWTSecretKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TagsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourcesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UsersTableName:
    Description: "Users DynamoDB table name"
    Value: !Ref UsersTable
  TagsTableName:
    Description: "Tags DynamoDB table name"
    Value: !Ref TagsTable
  ResourcesTableName:
    Description: "Resources DynamoDB table name"
    Value: !Ref ResourcesTable

